nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-preset.cjs
    spec: packages/yarn-plugin-preset/bundles/@yarnpkg/plugin-preset.js

yarnPath: .yarn/releases/yarn-4.12.0.cjs
